---
title: "Replace with Main Title"
author: "Your Name"
date: "`r Sys.Date()`"  # Uses current date
---


```{r echo=FALSE, message=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```


```{r}
testify <- 
  readXL("C:/Users/miken/Downloads/Mes cours/Projet-Statistiques/test_project.xls",
   rownames=FALSE, header=TRUE, na="", sheet="Variables", 
  stringsAsFactors=TRUE)
```

```{r}
summary(testify)
```


```{r}
library(abind, pos=17)
```


```{r}
library(e1071, pos=18)
```


```{r}
numSummary(testify[,c("agro.eco", "Association", "Autre.source.de.revenu", 
  "Charge.moy.ha", "Couverture.alimentaire", "Formation", "Nombre.d.années", 
  "Rendement..Kg.ha.", "Revenu.moy.ha", "Superficie..ha."), drop=FALSE], 
  statistics=c("mean", "sd", "IQR", "quantiles"), quantiles=c(0,.25,.5,.75,1))
```

```{r}
cor(testify[,c("agro.eco","Association","Autre.source.de.revenu",
  "Charge.moy.ha","Couverture.alimentaire","Formation","Nombre.d.années",
  "Rendement..Kg.ha.","Revenu.moy.ha","Superficie..ha.")], use="complete")
```

```{r}
with(testify, cor.test(Charge.moy.ha, Revenu.moy.ha, 
  alternative="two.sided", method="pearson"))
```

```{r}
RegModel.2 <- 
  lm(Charge.moy.ha~agro.eco+Association+Autre.source.de.revenu+Couverture.alimentaire+Formation+Nombre.d.années+Rendement..Kg.ha.+Revenu.moy.ha+Superficie..ha.,
   data=testify)
summary(RegModel.2)
```

```{r}
RegModel.3 <- 
  lm(Revenu.moy.ha~agro.eco+Association+Autre.source.de.revenu+Charge.moy.ha+Couverture.alimentaire+Formation+Nombre.d.années+Rendement..Kg.ha.+Superficie..ha.,
   data=testify)
summary(RegModel.3)
```

```{r}
RegModel.4 <- 
  lm(Revenu.moy.ha~agro.eco+Autre.source.de.revenu+Charge.moy.ha, 
  data=testify)
summary(RegModel.4)
```

